v-finance/camelot

camelot/admin/action/field_action.py

Replace icon for OpenFile field action

---

camelot/view/art.py

construction of invalid icons fails early instead of within qt slots

---

camelot/view/action_runner.py

Check if C++ progress dialog is deleted before using it

---

camelot/core/utils.py

Do not use session for load_translations()

---

camelot/view/controls/editors/floateditor.py
camelot/view/controls/editors/virtualaddresseditor.py

Deze testen falen:
[error] 0.07% vfinance.test.test_connector.test_report_import.LoanReportImportCase.test_import_loan_account_schedules_report: 5.0408s
[error] 0.05% vfinance.test.test_model.test_financial.test_report.FinancialReportCase.test_account_roles: 3.5773s
[error] 0.04% vfinance.test.test_model.test_financial.test_report.FinancialReportCase.test_premium_schedules_report: 2.7412s
[error] 0.04% vfinance.test.test_model.test_financial.test_report.FinancialReportCase.test_commissions_report: 2.7313s
[error] 0.04% vfinance.test.test_connector.test_report_import.LoanReportImportCase.test_import_loan_persons: 2.7022s
[error] 0.00% vfinance.test.test_connector.test_report_import.FinancialReportImportCase.test_1_generate_reports_to_import: 0.1528s
[error] 0.00% …

VFIN-1516: float editor group separator + VFIN-1519: QRegExp

---

camelot/view/controls/filter_widget.py
camelot/view/controls/tableview.py

vFinance starts & TableViews can now be opened

Continue Qt6 migration

---

camelot/admin/action/base.py
camelot/core/serializable.py
requirements.txt

dataclasses are built in as of python 3.7, available from pypi for 3.6

add state/mode serialization with dataclasses

---

camelot/admin/entity_admin.py
camelot/model/memento.py

Check __facade_args__ for 'editable' in EntityAdmin

---

camelot/admin/action/list_action.py
camelot/core/orm/entity.py
camelot/view/action_steps/change_object.py
camelot/view/action_steps/form_view.py
camelot/view/action_steps/item_view.py
camelot/view/controls/editors/one2manyeditor.py
camelot/view/proxy/collection_proxy.py
test/test_item_model.py
test/test_view.py

Disable EditActions for noneditable entities

---

camelot/core/orm/entity.py

first use of new facades

---

camelot/admin/action/list_action.py
camelot/admin/entity_admin.py
camelot/admin/not_editable_admin.py
camelot/admin/object_admin.py
camelot/core/item_model/__init__.py
camelot/core/item_model/proxy_registry.py
camelot/core/orm/entity.py
camelot/view/action_steps/change_object.py
camelot/view/action_steps/form_view.py
camelot/view/action_steps/item_view.py
camelot/view/controls/delegates/delegatemanager.py
camelot/view/controls/editors/one2manyeditor.py
camelot/view/import_utils.py
camelot/view/proxy/collection_proxy.py
test/test_action.py
test/test_item_model.py
test/test_view.py

Nog niet mergen aub, zie vraag bij code.

Make UpdateTableView serializable (contd.)

---

camelot/model/authentication.py
camelot/model/batch_job.py
camelot/model/memento.py
camelot/model/party.py

Refactored all ManyToOne relationships from camelot(main program)

---

camelot/model/authentication.py
camelot/model/batch_job.py
camelot/model/memento.py
camelot/model/party.py
camelot_example/model.py
test/snippet/admin_field_attribute.py
test/test_admin.py
test/test_orm/test_dict.py
test/test_orm/test_order_by.py

http://jenkins.vfinance.be/view/Pipeline%20Jobs/job/vFinance_pipeline_student1/44/

All relationships have been removed from camelot

---

camelot/admin/action/list_filter.py
camelot/admin/admin_route.py
camelot/admin/application_admin.py
camelot/admin/entity_admin.py
camelot/admin/object_admin.py
camelot/core/serializable.py
camelot/model/type_and_status.py
camelot/test/__init__.py
camelot/view/action_steps/application.py
camelot/view/action_steps/item_view.py
camelot/view/action_steps/select_object.py
camelot/view/controls/delegates/delegatemanager.py
test/test_action.py

Tests passed.
Ter info: Ik heb ook al het toolbar_area argument van get_list_toolbar_actions() verwijderd maar nog niet gepusht/getest.

Make UdateTableView.xxx_toolbar_actions serializable

---

camelot/view/action_steps/application.py

Refactored Layout

---

camelot/view/action_steps/change_object.py
camelot/view/action_steps/form_view.py
camelot/view/action_steps/gui.py
camelot/view/action_steps/print_preview.py
camelot/view/action_steps/select_file.py
camelot/view/action_steps/text_edit.py

Contains fixes for wrongly declared variables (changed them to be object-specific).
Also contains last ActionStep dataclass refactoring.

Refactored Camelot ActionSteps to dataclass

---

camelot/admin/action/application_action.py
camelot/admin/action/form_action.py
camelot/admin/action/list_action.py
camelot/admin/admin_route.py
camelot/admin/application_admin.py
camelot/admin/entity_admin.py
camelot/admin/object_admin.py
camelot/model/type_and_status.py
camelot/view/action_steps/item_view.py
camelot/view/action_steps/select_object.py
camelot/view/import_utils.py

Simplify action registration by using global instances + some fixes

---

camelot/admin/action/form_action.py
camelot/admin/application_admin.py
camelot/admin/object_admin.py
camelot/model/type_and_status.py
camelot/view/action_steps/change_object.py
camelot/view/action_steps/form_view.py
camelot/view/import_utils.py
test/test_admin.py

Er waren woensdag nog 2 tests die faalde (zie hieronder). Deze morgen zijn er problemen met Jenkins dus ik wacht tot de Jenkins server herstart is.
```
======================================================================
ERROR: test suite for <class 'vfinance.test.test_connector.test_accounting.InternalAccountingCase'>
----------------------------------------------------------------------
Traceback (most recent call last):
File "/vortex/x86_64-redhat-linux/default/lib/python3.8/site-packages/nose/suite.py", line 210, in run
self.setUp()
File "/vortex/x86_64-redhat-linux/default/lib/python3.8/site-packages/nose/suite.py", line 293, in setUp
self.setupContext(ancestor)
File "/vortex/x86_64-redhat-linux/default/lib/python3.8/site-packages/nose/suite.py", line 316, in setupContext …
```

Remove toolbar_area from get_related_toolbar_actions and get_from_toolbar_actions

---

camelot/view/action_steps/item_view.py
camelot/view/action_steps/select_object.py
camelot/view/controls/action_widget.py
camelot/view/controls/filter_widget.py
camelot/view/controls/tableview.py
camelot/view/proxy/collection_proxy.py
test/test_action.py

Add ChangeSelection to CollectionProxy

---

camelot/admin/action/field_action.py
camelot/admin/action/list_action.py
camelot/view/controls/action_widget.py
camelot/view/controls/editors/one2manyeditor.py
camelot/view/controls/tableview.py
camelot/view/proxy/collection_proxy.py

Connect CollectionProxy and TableView directly

---

camelot/admin/action/field_action.py
camelot/admin/action/list_action.py
camelot/view/action_steps/change_object.py
camelot/view/controls/delegates/customdelegate.py
camelot/view/controls/delegates/one2manydelegate.py
camelot/view/controls/editors/one2manyeditor.py
camelot/view/proxy/collection_proxy.py

Make One2ManyEditor work with field & list actions

---

camelot/admin/action/application_action.py
camelot/view/qml_view.py
camelot/view/workspace.py

Also add environment variable VFINANCE_OLD_TABLE to allow old table view to be used.
Testen zijn aan het draaien...

Create QmlView when creating DesktopWorkspace

---

camelot/admin/action/list_filter.py
camelot/view/action_steps/item_view.py
camelot/view/proxy/collection_proxy.py
camelot/view/qml_view.py
camelot/view/workspace.py

VFIN-1622 #comment Use C++ backend for QML TableView

---

camelot/view/action_steps/open_file.py

VFIN-1687 #comment Add checks to OpenFile to prevent segfault

---

camelot/admin/action/list_action.py
camelot/admin/action/list_filter.py
camelot/admin/entity_admin.py
camelot/admin/object_admin.py
test/test_action.py
test/test_admin.py

- Added priority level for filter strategies.
- Removed One2ManyFilter strategy as default field attribute for one2many relations.
- Added (not) empty operator for One2ManyFilter strategy.

VFIN-1665 Filter strategy priority level and one2many filter strategy extensions.

---

camelot/view/action_steps/item_view.py
camelot/view/item_view.py

VFIN-1622: ItemViewProxy now uses TableViewBackend

---

camelot/admin/action/list_action.py
camelot/admin/action/list_filter.py

VFIN-1622: shortcuts

---

camelot/view/action_steps/print_preview.py

VFIN-1740: Add assertions to verify thread affinity

---

camelot/admin/object_admin.py
camelot/view/action_steps/change_object.py
camelot/view/action_steps/crud.py
camelot/view/action_steps/form_view.py
camelot/view/controls/formview.py
camelot/view/forms.py
test/test_view.py

and only set action states once when constructing a form

reduce the number of used field attributes when constructing a form

---

camelot/admin/action/list_action.py
camelot/view/controls/editors/one2manyeditor.py
camelot/view/controls/tableview.py
camelot/view/proxy/collection_proxy.py
camelot/view/qml_view.py
test/test_action.py

De camelot unit testen werken terug. Om dit ook te doen werken dien ik nog wel de gui_context te zetten op de CollectionProxy, maar ik heb nog niet gevonden waar ik dit best kan doen (TBD).

VFIN-1975: Update selection through model

---

camelot/admin/action/application_action.py
camelot/admin/action/list_action.py
camelot/view/action_runner.py
camelot/view/action_steps/application.py
camelot/view/action_steps/crud.py
camelot/view/action_steps/gui.py
camelot/view/action_steps/item_view.py
camelot/view/qml_view.py

VFIN-1997: Start removing python gui_context

---

camelot/admin/action/list_action.py
camelot/test/action.py
camelot/view/action_steps/orm.py
camelot/view/proxy/collection_proxy.py
test/test_item_model.py

VFIN-1918: polish table view

---

camelot/view/action_steps/__init__.py
camelot/view/action_steps/application.py

VFIN-1918 #comment open table view message contains the settings group

---

camelot/model/batch_job.py

VFIN-2040 #comment translate sections into FR

---

camelot/view/action_runner.py

Heb dit lokaal getest door een raise toe te voegen in een actie en dit lijkt goed te werken.

VFIN-2065: Do not show exception dialog when running in offscreen mode

---

camelot/admin/object_admin.py
camelot/view/action_steps/item_view.py
camelot/view/action_steps/select_object.py
camelot/view/proxy/collection_proxy.py

Is dit voldoende? Een andere manier zou zijn om met een InitVar te werken en een parameter toe te voegen aan de Admin's get_list_actions() bijvoorbeeld.

VFIN-1918: Changes to columns + SelectObjects

---

camelot/view/action_steps/crud.py

VFIN-1918: Serialize field attributes for ComboBox delegate

---

test/test_item_model.py

Nodig na aanpassing ivm opvragen van data zonder kolommen.

VFIN-2202: Fix camelot tests

---

camelot/view/action_steps/crud.py
camelot/view/action_steps/item_view.py
camelot/view/controls/action_widget.py
camelot/view/crud_action.py

VFIN-2039: polish master branch

---

camelot/core/orm/entity.py

VFIN-2157 #comment return empty list if no discriminitor value

---

camelot/view/controls/delegates/booldelegate.py
camelot/view/controls/delegates/comboboxdelegate.py
camelot/view/controls/delegates/datedelegate.py
camelot/view/controls/delegates/datetimedelegate.py
camelot/view/controls/delegates/filedelegate.py
camelot/view/controls/delegates/floatdelegate.py
camelot/view/controls/delegates/integerdelegate.py
camelot/view/controls/delegates/languagedelegate.py
camelot/view/controls/delegates/localfiledelegate.py
camelot/view/controls/delegates/many2onedelegate.py
camelot/view/controls/delegates/monthsdelegate.py
camelot/view/controls/delegates/plaintextdelegate.py
camelot/view/controls/delegates/richtextdelegate.py
camelot/view/controls/delegates/texteditdelegate.py
camelot/view/controls/delegates/virtualaddressdelegate.py

VFIN-2452: Disable calls to set_item_editability

---

camelot/view/controls/delegates/booldelegate.py
camelot/view/controls/delegates/comboboxdelegate.py
camelot/view/controls/delegates/datedelegate.py
camelot/view/controls/delegates/datetimedelegate.py
camelot/view/controls/delegates/filedelegate.py
camelot/view/controls/delegates/floatdelegate.py
camelot/view/controls/delegates/integerdelegate.py
camelot/view/controls/delegates/languagedelegate.py
camelot/view/controls/delegates/localfiledelegate.py
camelot/view/controls/delegates/many2onedelegate.py
camelot/view/controls/delegates/monthsdelegate.py
camelot/view/controls/delegates/plaintextdelegate.py
camelot/view/controls/delegates/richtextdelegate.py
camelot/view/controls/delegates/texteditdelegate.py
camelot/view/controls/delegates/virtualaddressdelegate.py

This reverts commit 335af67564a2126de2fac71e0ba2fd77c5f13b02.

Revert "VFIN-2452 #comment Disable calls to set_item_editability"

---

camelot/core/backup.py
camelot/view/action_steps/select_file.py
camelot/view/requests.py

Added Deserialize to the `SaveFile`

VFIN-2742 Deserialize the SaveFile

---

camelot/admin/admin_route.py

Related to the [following PR](https://github.com/v-finance/vFinance/pull/2750)

#VFIN-2742 - Removes name validation for cli actions

---

camelot/admin/action/field_action.py
camelot/core/backup.py
camelot/core/files/storage.py
camelot/model/party.py
camelot/types/__init__.py

Since the PurePosixPath will not work when inputted with a windows path, purepath is the better option

Replaced PurePosixPath with PurePath

---

camelot/admin/action/field_action.py
camelot/core/files/storage.py
camelot/types/__init__.py
test/test_view.py

http://jenkins.vfinance.be/view/Pipeline%20Jobs/job/vfinance-pipeline-student1/95/ tests ok
vfinance nog WIP

Added verbose name field to storage, Storage can now choose verbose name

---

camelot/view/validator.py

VFIN-2844 Reworked RegexValidator to only change position after formatting valid values

---

camelot/admin/action/list_action.py
camelot/admin/object_admin.py

This includes:
* secondary discriminator selection
* setting the discriminator value
* overrulable types-based modes

VFIN-2840 Integrated moved One2ManyAddNewObject behaviour into AddNewObjectMixin.

---

camelot/data/types/__init__.py

Required for https://github.com/v-finance/vFinance/pull/3458

VFIN-3068 - Changed the type_str to make annotated types work

---

camelot/core/orm/entity.py

Camelot changes for PR: https://github.com/v-finance/vFinance/pull/3669

VFIN-3068 - Removed EntityBase.get & EntityBase.get_by
